const constant: any = {
  FETCH_USER: "FETCH_USER",
  FETCH_USER_SUCCESS: "FETCH_USER_SUCCESS",
  FETCH_ERROR: "FETCH_ERROR",
  INCREMENT: "INCREMENT",
  DECREMENT: "DECREMENT",
};

export { constant };
